### ISSUE TITLE
Struggling to get the image to run

### ISSUE THREAD

**Issue by Bitmasss** [infinytum/ubnt-cloudkey-docker#1]
Hey, hope you are well first and foremost. Thanks for this image. I've downloaded and built it, I'm just not sure what I'm doing wrong, or if I've misinterpreted something along the way

I'm using 18.04 for reference.

I'm trying to get it to run and getting this error:

dlers)
[ 2340.097787] pre-start.sh[22]: postgresql is not active, start service
[ 2340.098260] pre-start.sh[22]: > systemctl start postgresql
[FAILED] Failed to start Postgres Initializor.
See 'systemctl status initdb.service' for details.
         Starting PostgreSQL Cluster 9.6-main...
[FAILED] Failed to start PostgreSQL Cluster 9.6-main.
See 'systemctl status postgresql@9.6-main.service' for details.
         Starting PostgreSQL RDBMS...
[  OK  ] Started PostgreSQL RDBMS.
[ 2340.226317] pre-start.sh[22]: start postgresql service success
         Starting LSB: exim Mail Transport Agent...
         Starting UniFi Protect...
[  OK  ] Started LSB: exim Mail Transport Agent.
[  OK  ] Started UniFi access controller.
[ 2341.301178] pre-start.sh[22]: psql: could not connect to server: No such file or directory
[ 2341.302172] pre-start.sh[22]:        Is the server running locally and accepting
[ 2341.304327] pre-start.sh[22]:        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
[ 2341.309518] pre-start.sh[22]: psql createuser ulp-go
[ 2341.366088] pre-start.sh[22]: createuser: could not connect to database postgres: could not connect to server: No such file or directory
[ 2341.367353] pre-start.sh[22]:        Is the server running locally and accepting
[ 2341.370270] pre-start.sh[22]:        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
[FAILED] Failed to start UniFi ULP-GO Backend service.
See 'systemctl status ulp-go.service' for details.
[DEPEND] Dependency failed for UniFi Core.
[ 2341.377526] pre-start.sh[22]: create user failed
[ 2341.377766] pre-start.sh[22]: ERROR<[1]>: create user ulp-go
[ 2341.377965] pre-start.sh[22]: ERROR<[1]>: init db failed
[ 2341.378528] pre-start.sh[22]: ERROR<[1]>: run failed

Any help would be appreciated.

**Comment by infinytum** [comment]
I think its a permission error with the postgres volume. Somehow initdb was not able to bootstrap the postgres db.

I'd suggest `chown -R 107:110 <path to volume>`

**Comment by infinytum** [comment]
Or you could just try a run without volumes at all, so we are sure its something to do with the volumes. You will be able to install it, but after a restart of the container its all gone of course.

**Comment by Bitmasss** [comment]
Ok, it seems to start without the recommended --network=host

It seems to boot, but the protect screen seems to hang. Looks like I need to play around more. Thanks for the response.

**Comment by infinytum** [comment]
If you are using Brave, disable shields for the protect page to load

**Comment by Bitmasss** [comment]
It was doing the same on Firefox and Chrome, interestingly I could view it at protect.ui.com just not locally. However, it wouldn't discover my cameras - perhaps to the local of --network=host?

**Comment by infinytum** [comment]
Yeap, thats why I suggest using --network


You dont have a postgres installed on your system do you? I really cant think of a reason why --network broke the DB init script.

**Comment by infinytum** [comment]
I think you could manually set the Controller URL on the camera UI though?

**Comment by Bitmasss** [comment]
Ok, that was it, I already had postgres installed locally. Uninstalled completely, re run with --network=host and works a charm now. Even found my cameras and works locally also. Great stuff, thanks.

**Comment by infinytum** [comment]
Cool! Enjoy fiddling around with it :)

Obligatory Disclaimer: Please remember that I don't recommend using it in production for multiple reasons (including possible legal).
